version: '3'

services:
    nginx:
        restart: always
        image: nginx:1.21-alpine
        ports:
            - 8000:8000
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/app/static
    wsgiserver:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/static
            - /home/rosenv/PycharmProjects/mlappdeploy/db.sqlite3:/app/db.sqlite3
        expose:
            - 8000

volumes:
    static_volume: {}