# Generated by Django 3.1.7 on 2021-08-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_auto_20210716_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtest',
            name='parent_mlalgorithm_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_1', to='endpoints.mlalgorithm'),
        ),
        migrations.AlterField(
            model_name='abtest',
            name='parent_mlalgorithm_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_mlalgorithm_2', to='endpoints.mlalgorithm'),
        ),
    ]
